### PR TITLE
Initial project for the JetBrains Plugin.

### PR DESCRIPTION
**Pull request by jason-bloom**
Initial basis for the plugin created by following both guides:

- https://www.jetbrains.org/intellij/sdk/docs/tutorials/build_system/prerequisites.html#creating-a-gradle-based-intellij-platform-plugin-with-new-project-wizard. 
- https://www.jetbrains.org/intellij/sdk/docs/tutorials/action_system/working_with_custom_actions.html

### CODE REVIEW

**Comment by CheyenneSlager** [comment]
Shouldn't the "build" folder be in the gitignore?

**Comment by jason-bloom** [comment]
> Shouldn't the "build" folder be in the gitignore?

I think you are correct, should the .gradle also be added?

**Comment by CheyenneSlager** [comment]
Yes, the ".gradle" folder should also be ignored by git. It contains a lot of output files, which are automatically generated when the application is run.

**Comment by CheyenneSlager** [comment]
Overal this is a really good basis to start building upon.

**Comment by jason-bloom** [comment]
Ok, thank you. I have updated the .gitignore and included the directories.
https://github.com/MahmoudRe/JetBrainsPlugin/tree/1cd5936ebb5492fb23b60eca0dfd64986cb9c844

**Review by CheyenneSlager — APPROVED** [review]

**Pull request merged**
